name: CI/CD Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Ejecutar Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependencias
        run: npm install

      - name: Configurar Variables de Entorno
        run: echo "MONGO_TEST=${{ secrets.MONGO_TEST }}" >> .env

      - name: Ejecutar Tests
        run: npm test

  deploy:
    name: Deploy a Vercel
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Autenticar en Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy a Producción en Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
